# Database
spring.datasource.url=jdbc:mysql://localhost:3306/smartshelfx
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=smartshelfx-super-secret-key-2024-make-it-long
jwt.expiration=86400000

ml.service.url=http://localhost:5000